### ISSUE TITLE
[Request]: theme s

### ISSUE THREAD

**Issue by daveberzack** [skedwards88/crossjig#40]
### What is your request?

Just an idea: have you considered doing puzzles with themes, so words are related? You wouldn't necessarily give the theme upfront, but it could be satisfying to recognize a theme afterwards. This isn't a dev task, it's a content generation task. Might involve more work then you'd care to deal with, but thought I'd mention it in case you hadn't considered it.

I really dig the game, BTW.

**Comment by skedwards88** [comment]
I love this idea! I think it could be fun to make the daily puzzle have occasional themes and/or fun for users to create custom puzzles that they can share with friends. It should be pretty straightforward for me to update the code to return a hardcoded puzzle when given a specific query string in the URL. I'll work on that this weekend.

If you have specific puzzles in mind, feel free to post them here! They just need to be a square grid of letters (min 8x8, max 12x12), and the words need to be found in [this list](https://github.com/skedwards88/word_lists/blob/main/compiled/commonWords.json). The game logic will take care of breaking the puzzle into pieces.

Thanks again for sharing this idea. I'm excited that the game is spreading beyond my immediate friends.

**Comment by skedwards88** [comment]
I have a draft PR here: https://github.com/skedwards88/crossjig/pull/41. Right now, the app can parse a query string into a custom puzzle. Next, I'll add a way for players to generate and share custom puzzles in the UI, and I'll add some themed puzzles to the daily challenge.

**Comment by skedwards88** [comment]
@daveberzack You can now create and share custom puzzles! (Refresh or close/reopen the app until the version listed at the bottom of the info page is > 3.0.0, then click the pencil icon.) You can also expect to see some themed daily puzzles in the future. Thanks again for sharing this suggestion!

**Comment by daveberzack** [comment]
Oh wow. I actually got a response from a feature request. cool.
It would be nice to be able to specify how the pieces divide.

Another feature request: Add a timer. With my 5minute.games portal, I'm
planning to add social features, where players can share their results. I
think players might enjoy playing against a clock (perhaps optionally) and
that could enable competitive play.

Dave Berzack
