### ISSUE TITLE
[Bug]: crossjig.com scrolls in Android Chrome

### ISSUE THREAD

**Issue by jorendorff** [skedwards88/crossjig#6]
### Version

whatever is deployed on crossjig.com right now? (bug template says this is in the heart menu, but I don't see it)

### Platform

Motorola One 5G Ace running Android 11 and Google Chrome

### What is wrong?

When I run it as a PWA, from my home screen, it's fine, but when I visit crossjig.com in Chrome, in portrait orientation, the whole `div.App` is a little bigger than the available area, so it scrolls vertically by about 80px (and 10px horizontally).

On the device, it looks like this:

![Image](https://github.com/skedwards88/crossjig/assets/283361/1829ec35-414f-4312-999d-f4ab387a03c9)

When I debug this using Chrome Devtools over USB, it looks like this:

![Image](https://github.com/skedwards88/crossjig/assets/283361/1e6cf041-376d-414a-b7e0-a261a59b18a6)

**Comment by skedwards88** [comment]
Thanks for reporting this! I have a PR here that fixes it on my phone (Pixel 7, Android version 13): https://github.com/skedwards88/crossjig/pull/7 Are you interested in testing it out before I merge @jorendorff ?

**Comment by skedwards88** [comment]
> bug template says this is in the heart menu, but I don't see it

Also thanks for pointing this out. I've fixed the issue template in https://github.com/skedwards88/crossjig/commit/e8415a0d5e568558fc43f7a1e38ba85efecc37d5 now.
